line.bot:
  channel-token: 'EC8za3g/Mj5cemyHwVCS7LaBp0rL6MGGkDt2OxacOHivhPZN8lut7S+bSnvEejDfGwpVbRIiYGnP5oz5XeXKsf6qjuTU39cCHZTcyzbgIPLZxVB5LWZWMwMVVhHF/4gjg1arIj/24RC1Jd0DG5Y+vwdB04t89/1O/w1cDnyilFU='
  channel-secret: '064a364b93ea3a31c9517506e6ca436a'
  handler.path: /callback
